PLUGIN_NAME=		wan-ha-dhcp
PLUGIN_VERSION=		0.1
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		CARP-aware high availability for DHCP WANs
PLUGIN_MAINTAINER=	28662377+bryanwieg@users.noreply.github.com

.include "../../Mk/plugins.mk"
