<ul class="nav nav-tabs" role="tablist">
    <li class="active"><a data-toggle="tab" href="#watcher-mappings">{{ lang._('Mappings') }}</a></li>
    <li><a data-toggle="tab" href="#dhcp-records">{{ lang._('Active DHCP Records') }}</a></li>
</ul>
<div class="content-box tab-content">
<div id="watcher-mappings" class="tab-pane fade in active"><div class="table-responsive"><table id="grid-dhcp-watcher" class="table table-condensed table-hover table-striped" data-editDialog="dialogEditBindWatcher"><thead><tr><th data-column-id="enabled" data-formatter="rowtoggle">{{ lang._('Enabled') }}</th><th data-column-id="dhcp_source">{{ lang._('DHCP Source') }}</th><th data-column-id="hostname_suffix">{{ lang._('Primary Zone') }}</th><th data-column-id="tsigkey">{{ lang._('TSIG Key') }}</th><th data-column-id="uuid" data-identifier="true" data-visible="false">{{ lang._('ID') }}</th><th data-column-id="commands" data-formatter="commands">{{ lang._('Commands') }}</th></tr></thead><tbody></tbody><tfoot><tr><td colspan="6"><button data-action="add" type="button" class="btn btn-xs btn-primary"><span class="fa fa-plus"></span> {{ lang._('Add') }}</button></td></tr></tfoot></table></div></div>
<div id="dhcp-records" class="tab-pane fade"><div class="alert alert-info">{{ lang._('Records are created from active DHCPv4 leases and cannot be edited here.') }}</div><div class="table-responsive"><table id="grid-dhcp-records" class="table table-condensed table-hover table-striped"><thead><tr><th data-column-id="hostname">{{ lang._('Hostname') }}</th><th data-column-id="domain">{{ lang._('Primary Zone') }}</th><th data-column-id="address">{{ lang._('IP Address') }}</th><th data-column-id="mac">{{ lang._('MAC Address') }}</th><th data-column-id="ends">{{ lang._('Expires') }}</th><th data-column-id="source">{{ lang._('Source') }}</th></tr></thead><tbody></tbody></table></div></div>
</div>
{{ partial("layout_partials/base_dialog",['fields':formDialogEditBindWatcher,'id':'dialogEditBindWatcher','label':lang._('Edit DHCP Watcher Mapping')])}}
<script>$(document).ready(function() { $('#grid-dhcp-watcher').UIBootgrid({search:'/api/bind/watcher/search_mapping',get:'/api/bind/watcher/get_mapping/',set:'/api/bind/watcher/set_mapping/',add:'/api/bind/watcher/add_mapping/',del:'/api/bind/watcher/del_mapping/',toggle:'/api/bind/watcher/toggle_mapping/'}); $('#grid-dhcp-records').UIBootgrid({search:'/api/bind/dhcprecord/search_record',options:{selection:false,rowSelect:false}}); });</script>
