#!/bin/sh
# PROVIDE: wan_ha_dhcp
# REQUIRE: LOGIN
# KEYWORD: shutdown

# rc.subr consumes the service metadata below.
# shellcheck disable=SC2034
. /etc/rc.subr

name="wan_ha_dhcp"
rcvar="wan_ha_dhcp_enable"
pidfile="/var/run/wan-ha-dhcp/supervisor.pid"
command="/usr/sbin/daemon"
command_args="-f -r -R 1 -P ${pidfile} -p /var/run/wan-ha-dhcp/controller.pid /usr/local/bin/python3 /usr/local/opnsense/scripts/wan_ha_dhcp/wan_ha_dhcp.py serve"
start_precmd="wan_ha_dhcp_start_pre"
stop_precmd="wan_ha_dhcp_stop_pre"

wan_ha_dhcp_start_pre()
{
    /usr/local/bin/python3 /usr/local/opnsense/scripts/wan_ha_dhcp/wan_ha_dhcp.py resume
}

wan_ha_dhcp_stop_pre()
{
    # Inhibit promotion and verify fencing before terminating the supervisor.
    # A failed fence leaves the running controller alive to retry.
    /usr/local/bin/python3 /usr/local/opnsense/scripts/wan_ha_dhcp/wan_ha_dhcp.py suspend
}

load_rc_config "${name}"
: "${wan_ha_dhcp_enable:=YES}"
run_rc_command "$1"
