PLUGIN_NAME=		dhcp-interface-ha
PLUGIN_VERSION=		0.2
PLUGIN_REVISION=	15
PLUGIN_CONFLICTS=	wan-ha-dhcp
PLUGIN_COMMENT=		CARP-aware high availability for a DHCP client interface
PLUGIN_MAINTAINER=	28662377+bryanwieg@users.noreply.github.com

.include "../../Mk/plugins.mk"
