#!/bin/sh
# PROVIDE: dhcp_interface_ha
# REQUIRE: LOGIN
# KEYWORD: shutdown

# rc.subr consumes the service metadata below.
# shellcheck disable=SC2034
. /etc/rc.subr

name="dhcp_interface_ha"
rcvar="dhcp_interface_ha_enable"
pidfile="/var/run/dhcp-interface-ha/supervisor.pid"
command="/usr/sbin/daemon"
command_args="-f -r -R 1 -P ${pidfile} -p /var/run/dhcp-interface-ha/controller.pid /usr/local/bin/python3 /usr/local/opnsense/scripts/dhcp_interface_ha/dhcp_interface_ha.py serve"
start_precmd="dhcp_interface_ha_start_pre"
stop_precmd="dhcp_interface_ha_stop_pre"

dhcp_interface_ha_start_pre()
{
    /usr/local/bin/python3 /usr/local/opnsense/scripts/dhcp_interface_ha/dhcp_interface_ha.py resume
}

dhcp_interface_ha_stop_pre()
{
    # Inhibit promotion and verify fencing before terminating the supervisor.
    # A failed fence leaves the running controller alive to retry.
    /usr/local/bin/python3 /usr/local/opnsense/scripts/dhcp_interface_ha/dhcp_interface_ha.py suspend
}

load_rc_config "${name}"
: "${dhcp_interface_ha_enable:=YES}"
run_rc_command "$1"
