[status]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/dhcp_interface_ha/dhcp_interface_ha.py status --from-config
parameters:
type:script_output
message:Read DHCP Interface HA controller status

[apply]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/dhcp_interface_ha/dhcp_interface_ha.py apply
parameters:
type:script_output
message:Apply DHCP Interface HA controller configuration

[prepare_setup]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/dhcp_interface_ha/dhcp_interface_ha.py prepare_setup
parameters:
type:script_output
message:Prepare DHCP Interface HA device during disabled setup
