PLUGIN_NAME=		bind-rp
PLUGIN_VERSION=		1.36
PLUGIN_REVISION=	6
PLUGIN_COMMENT=		BIND domain name service
PLUGIN_CONFLICTS=	bind
PLUGIN_DEPENDS=		bind920
PLUGIN_MANIFEST_DEPENDS=	opnsense: { version: "26.1.11_10", origin: "opnsense/opnsense" }
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
