PLUGIN_NAME=		bind-rp
PLUGIN_VERSION=		1.36
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		BIND domain name service
PLUGIN_PACKAGE_CONFLICT=	os-bind
PLUGIN_DEPENDS=		bind920
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
