PLUGIN_NAME=		bind-rp
PLUGIN_VERSION=		26.1
PLUGIN_REVISION=	5
PLUGIN_COMMENT=		BIND domain name service
PLUGIN_CONFLICTS=	bind
PLUGIN_DEPENDS=		bind920
PLUGIN_DEPEND_FORMULA=	bind920 >= 9.20.26
PLUGIN_DEPEND_FORMULA_DEPENDS=	bind920
PLUGIN_MANIFEST_DEPENDS=	opnsense: { version: "26.1.11_10", origin: "opnsense/opnsense" }
PLUGIN_MAINTAINER=	m.muenz@gmail.com

.include "../../Mk/plugins.mk"
