[status]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/wan_ha_dhcp/wan_ha_dhcp.py status --from-config
parameters:
type:script_output
message:Read WAN HA DHCP controller status

[apply]
command:/usr/local/bin/python3 /usr/local/opnsense/scripts/wan_ha_dhcp/wan_ha_dhcp.py apply
parameters:
type:script_output
message:Apply WAN HA DHCP controller configuration
